In [1]:
from utilities import *

In [63]:
contents = parsing_multi("day_3_pz.txt")

In [29]:
def find_max_min_occur_char(lst):
    char_count = {}
    
    for char in lst:
        if char in char_count.keys():
            char_count[char] += 1
        else:
            char_count[char] = 1
    
    max_val = 0
    max_char = 0

    min_val = len(contents)
    min_char = 0

    for k, v in char_count.items():
        if v > max_val:
            max_val = v
            max_char = k
    
    for k, v in char_count.items():
        if v < min_val:
            min_val = v
            min_char = k

    return [max_char,min_char]

def bin_to_val(lstt):
    summ = 0
    end = len(lstt) - 1
    for i in range(0, len(lstt)):
        summ += int(lstt[i])*(2**(end))
        end -= 1     
    return summ

In [71]:
gamma_rate = list()
epsilon_rate = list()
for i in range(0, len(contents[0])):
    column_wise = list()
    for content in contents:
        column_wise.append(content[i])
    gamma_rate.append(find_max_min_occur_char(column_wise)[0])
    epsilon_rate.append(find_max_min_occur_char(column_wise)[1])


g_rate = bin_to_val(gamma_rate)
e_rate = bin_to_val(epsilon_rate)
print(g_rate * e_rate)

1025636


In [ ]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

model = ols('column1 ~ group', data=df).fit()

anova_table = sm.stats.anova_lm(model, typ=2)
print(anova_table)

In [3]:
def rev(s):
    '''
    input:
    s -> an input string consisting of multiple words
    
    output:
    rev_s -> an output string consisting of the same words, but in reverse order
    '''
    rev_s = ""
    
    # Your code starts here
    words = s.split(" ")
    rev_w = words[::-1]
    rev_s = " ".join(rev_w)

    return rev_s

In [4]:
ss = "this is a sample text"
rev(ss)

'text sample a is this'

In [6]:
my_list = ["Woww!", "#46778", "Hello", "Good Morning", "890"]

l = [n for n in my_list if n.isalpha() or n.isdigit()]
print(l)

['Hello', '890']


In [7]:
def custome_func(arr,n):
    length = len(arr)
    n = n% length
    lst = []
    for i in range(length):
        new_index = (i + n) % length
        lst.append(arr[new_index])
    return lst

orig_lst = [10,4,5,3,11]
n = 2
new_lst = custome_func(orig_lst, n)
print(new_lst)


[5, 3, 11, 10, 4]


In [8]:
sampleDict = {"class":{"student":{"name": "Mike", "marks": {"physics": 70, "history": 80}}}}

In [12]:
sampleDict["class"]["student"]["marks"]["history"]

80

In [44]:
import numpy as np
import math

In [45]:

def calculate_min(a,b,c,d,n):
    num = None
    min_val = list()
    #YOUR CODE GOES HERE
    for i in range(1,n):
        val = a*math.pow(i,3) + b*math.pow(i,2) + c*math.pow(i,1) + d
        min_val.append(val)
    
    num = min_val.index(min(min_val)) + 1
    return num

In [46]:
calculate_min(1,5,-3,1, 200)

1

In [47]:
a = np.array([10,52,62,16,16,54,453])

np.argsort(a)


array([0, 3, 4, 1, 5, 2, 6], dtype=int64)

In [49]:
 arr= np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [51]:
arr[arr[:,0] > 3 , 1:]

array([[5, 6],
       [8, 9]])

In [59]:
n_array = np.array([0,1,0,2,0,0,3,0,5,7,0,0,8])
np.where(n_array == 0)[0]

array([ 0,  2,  4,  5,  7, 10, 11], dtype=int64)

In [63]:
np.diagonal(arr).sum

<function ndarray.sum>